CREATE DATABASE IF NOT EXISTS bd_autores;
CREATE DATABASE IF NOT EXISTS bd_libros;
CREATE DATABASE IF NOT EXISTS bd_usuarios;
CREATE DATABASE IF NOT EXISTS bd_inventario;
CREATE DATABASE IF NOT EXISTS bd_pedidos;
CREATE DATABASE IF NOT EXISTS bd_pagos;
CREATE DATABASE IF NOT EXISTS bd_resenas;
CREATE DATABASE IF NOT EXISTS bd_notificaciones;
