server.port=8090

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Ruta libro-service
spring.cloud.gateway.server.webflux.routes[0].id=libro-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://libro-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/libros/**

# Ruta autor-service
spring.cloud.gateway.server.webflux.routes[1].id=autor-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://autor-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/autores/**

# Ruta usuario-service
spring.cloud.gateway.server.webflux.routes[2].id=usuario-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://usuario-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/usuarios/**

# Ruta pedido-service
spring.cloud.gateway.server.webflux.routes[3].id=pedido-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://pedido-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/pedidos/**

# Ruta pago-service
spring.cloud.gateway.server.webflux.routes[4].id=pago-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://pago-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/pagos/**

# Ruta inventario-service
spring.cloud.gateway.server.webflux.routes[5].id=inventario-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://inventario-service
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/inventario/**

# Ruta resena-service
spring.cloud.gateway.server.webflux.routes[6].id=resena-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://resena-service
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/resenas/**

# Ruta notificacion-service
spring.cloud.gateway.server.webflux.routes[7].id=notificacion-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://notificacion-service
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/v1/notificaciones/**

# Ruta generos (dentro de libro-service)
spring.cloud.gateway.server.webflux.routes[8].id=genero-service
spring.cloud.gateway.server.webflux.routes[8].uri=lb://libro-service
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/v1/generos/**